name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo
      - name: Checkout
        uses: actions/checkout@v4

      # Paso 2: Configuraci贸n de PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug

      # Paso 3: Configuraci贸n de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Paso 4: Instalar dependencias de Node.js
      - name: Install Node Dependencies
        run: npm ci --legacy-peer-deps

      # Paso 5: Compilar assets frontend
      - name: Build Assets
        run: npm run build

      # Paso 6: Instalar dependencias de PHP
      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Paso 7: Copiar archivo de entorno
      - name: Copy Environment File
        run: cp .env.example .env

      # Paso 8: Generar clave de aplicaci贸n
      - name: Generate Application Key
        run: php artisan key:generate

      # Paso 9: Ejecutar pruebas
      - name: Run Tests
        run: ./vendor/bin/pest
